### ISSUE TITLE
Cookie value cannot have an equals ('=') sign inside it

### ISSUE THREAD

**Issue by JPScerri** [BitzArt/Blazor.Cookies#13]
When you try to retrieve a cookie value that has an equal ('**=**') sign in the string, eg **x=1**, it will throw an error:
**Invalid Cookie Format: key=x=1**

**Comment by YuriyDurov** [comment]
Hello @JPScerri, please check this issue: #8

**Comment by JPScerri** [comment]
Noted. Thanks.
Cookies cannot have = sign by design. Encode and Decode if you need them.
