### ISSUE TITLE
Remove and add again, Null, direct SetAsync value will not change without removing

### ISSUE THREAD

**Issue by HuaFangYun** [BitzArt/Blazor.Cookies#14]
![image](https://github.com/user-attachments/assets/c2c61227-8cf4-4cf9-b540-e3929e866434)
I use the writing shown in the figure in CustomAuthenticationStateProvider : AuthenticationStateProvider. When a token is updated, after removing it and then adding it, the added value is Null. If it is OK to use a new variable, I would like to ask how to handle this.

**Comment by YuriyDurov** [comment]
Hello @HuaFangYun 

1. Are we talking about Static SSR or interactive rendering? Prerendering works just like Static SSR.

2. This is the intended behavior for Static SSR (or prerendering). The user's cookies are not updated until you finish processing the current request. The updated cookies will be attached to the http response when you have finished processing the page. So you will only be able to see that the cookies have updated when the user sends their next request.

3. You don't need to remove the cookie before setting the updated value. Setting a new value will overwrite the existing value in case it already exists.

4. We have an [auth package](https://github.com/BitzArt/Blazor.Auth) for Blazor, you could try it.

**Comment by HuaFangYun** [comment]
![image](https://github.com/user-attachments/assets/86da6193-60c8-4816-98e0-d99bfcecdb15)
![image](https://github.com/user-attachments/assets/bb7080bd-8a13-408e-a19e-de225fab51ea)
I feel that in your reply, I use the InteractiveServer model, and I have no problem adding and deleting it in the Blazor component. I use it in the CustomAuthenticationStateProvider : AuthenticationStateProvider authorization code to update the Token after the Token expires and regain it. Currently, I am in the Token update scheme, and it is invalid. Updating the current Key is invalid, and if I use a new Key , the value is correct.

**Comment by HuaFangYun** [comment]
![image](https://github.com/user-attachments/assets/83984b1f-3396-4198-892d-512e2463b4cc)
Instead of using removal, the SetAsync method is used directly, where new values cannot be updated. What is regained is still the old value. Is it a problem with my use here? How do I need to correct it. thank

**Comment by YuriyDurov** [comment]
InteractiveServer render mode includes prerendering, which works just like Static SSR, where this is the intended behavior.

You need to wait for the current http request to finish before you are able to see the updated cookies.

**Comment by HuaFangYun** [comment]
Okay. Thank you. Let me think about how my code can be transformed. thank
