### ISSUE TITLE
No cookies?

### ISSUE THREAD

**Issue by sam-wheat** [BitzArt/Blazor.Cookies#5]
I am writing a Blazor 8 app.  My app does not have a server and a client project, just server.
I added `builder.AddBlazorCookies();`, and I inject `ICookieService`.
Problem is that my Logout method says there are no cookies:
![image](https://github.com/BitzArt/Blazor.Cookies/assets/16885210/75f77607-aeaa-4c0f-8249-8c7fb0b94b47)

When I look in the browser I see cookies:

![image](https://github.com/BitzArt/Blazor.Cookies/assets/16885210/60ec7726-40fd-4d7f-b13d-a7365ebde094)

My app uses Azure OIDC:

	builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
		.AddMicrosoftIdentityWebApp(options => {

			builder.Configuration.Bind("AzureAd", options);
			options.Events.OnTokenValidated += OnTokenValidatedFunc;
		})
		.EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
		.AddMicrosoftGraph(builder.Configuration.GetSection("DownstreamApi"))
		.AddInMemoryTokenCaches();

My goal here is to sign out the user and redirect them to `/`.

**Comment by YuriyDurov** [comment]
@sam-wheat Hello,

The mentioned Cookies are likely `HttpOnly`.

`HttpOnly` Cookies will only be available while prerendering, or in [Static SSR](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0), as this is the only time when an HTTP request from the user to Blazor Server exists - and `HttpOnly` Cookies can be accessed through it.

While Server or Client Blazor interactivity, `Blazor.Cookies` uses JSInterop for interacting with Cookies, and thus can only access those Cookies that are not flagged as `HttpOnly`.

Hope this helps.

**Comment by sam-wheat** [comment]
@YuriyDurov thank you for your reply.  I am wondering how to clear the cookies, or how to get the name of the cookie that is to be cleared.  According to [this document](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-a-sign-out-request) the following has to happen:

![image](https://github.com/BitzArt/Blazor.Cookies/assets/16885210/5f1182de-6170-4e8f-ac50-e77c5e50ed41)
 
How do I get the name of the cookie to clear?
Logout method:

	var httpClient = httpFactory.CreateClient("auth");
	await httpClient.GetAsync("tenantid/oauth2/v2.0/logout?post_logout_redirect_uri=/");
	cookieService.RemoveAsync("????");  // Need cookie name
	NavigationManager.NavigateTo("/");

**Comment by YuriyDurov** [comment]
@sam-wheat 

You should be able to remove HttpOnly cookies while prerendering any page of your Blazor app, or while rendering any page in Static SSR

**Comment by sam-wheat** [comment]
Thank you
