### ISSUE TITLE
Trying to use this in OpenSilver which requires netstandard2.0 support.

### ISSUE THREAD

**Issue by scastria** [BitzArt/Blazor.Cookies#7]
I am not exactly sure if I should pass in the ICookieService to my OpenSilver netstandard2.0 project or not.  However, when I try, the BitzArt.Blazor.Cookies package only support .net8 which OpenSilver does not yet support.

**Comment by YuriyDurov** [comment]
Hello @scastria 

**Blazor.Cookies** are made with **Blazor** in mind, more specifically with something known as **Blazor United**, which came out as part of dotnet 8.

The whole idea behind this package is to provide you with a single interface to interact with cookies, which has different implementations for different **Blazor United** [render modes](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes) - which were unified into a single application template in dotnet 8.

This package figures out the current render mode and then provides an implementation suitable for that render mode.

Before dotnet 8, **Blazor** applications were split into server-side-rendered and client-side-rendered ones. So I do not really see a reason for this package to support anything below dotnet 8.

You can always implement your own solution that would support netstandard and satisfy your requirements.
