### ISSUE TITLE
Can cookies have "=" in the value?

### ISSUE THREAD

**Issue by scastria** [BitzArt/Blazor.Cookies#8]
I converted my cookie value to base64 and stored it.  However, when I tried to read it back, I get "Invalid cookie format" because this package is splitting the string on the equals sign.  Base64 uses equals signs causing the error.  Are cookies allowed to have equals signs inside the value?

**Comment by YuriyDurov** [comment]
Hello @scastria,

Equals signs are treated as separators in cookies, and thus can not be used in the value.

You could try [encoding](https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.urlencode) your value before setting it in the cookie, and [decoding](https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.urldecode) it when reading it back.

Also, equals signs are just for padding in base64, so you could probably just trim those, too. It should not affect the actual value.
